---

# Config jsons creation flag
special_config: false

# Path where configs are saved
special_config_dir: /etc/special-configs

# Special edge-proxy configs
edge_proxy_config: false
edge_proxy_config_dir: /etc/edge-proxy-configs

# Service edge config jsons creation flag
value_edge_config: false

# Path where service edge configs are saved
edge_config_dir: /etc/edge-configs/{{ global.service_name }}

values:
    edge_config:
        secret:
            enabled: "{{ EDGE_GLOBAL_SECRET_ENABLED | default(false) }}"
            edge_ssl_require_client_certs: true
            edge_ssl_config_trust_file: "{{ EDGE_SSL_CONFIG_TRUST_FILE | default('/etc/proxy/tls/sidecar/rootCA.crt') }}"
            edge_ssl_config_certificate_path: "{{ EDGE_SSL_CONFIG_CERTIFICATE_PATH | default('/etc/proxy/tls/sidecar/edge.crt') }}"
            edge_ssl_config_key_path: "{{ EDGE_SSL_CONFIG_KEY_PATH | default('/etc/proxy/tls/sidecar/edge.key') }}"
    edge:
        egress:
            secret:
                enabled: true
                mount_point: /etc/proxy/tls/sidecar
                secret_keys:
                    cert: edge.crt
                    key: edge.key
                    ca: rootCA.crt
        ingress:
            secret:
                enabled: true
                mount_point: /etc/proxy/tls/edge
                secret_keys:
                    cert: edge.crt
                    key: edge.key
                    ca: rootCA.crt
    catalog:
        catalogEnabled: true
        controlEnabled: true
        serviceName: catalog
        observablesEnabled: false
        port: 9080
        enableInstanceMetrics: 'true'
        capability: 'Mesh'
        documentation: "/services/catalog/latest/"
        name: "Grey Matter Catalog"
        owner: 'Decipher'
        data_prefix: "/data"
        version: 1.0.1
        minInstances: 1
        maxInstances: 1
        secret:
            enabled: true
            secret_name: sidecar-certs
            mount_point: /etc/proxy/tls/sidecar
            insecure: true
            secret_keys:
                cert: /etc/proxy/tls/sidecar/catalog.crt
                key: /etc/proxy/tls/sidecar/catalog.key
                ca: /etc/proxy/tls/sidecar/rootCA.crt
        # routes:
        #     - '/services/catalog/{{ catalog.version }}'
        #     - '/services/catalog/{{ catalog.version }}/'
    idata:
        catalogEnabled: true
        controlEnabled: true
        name: 'Grey Matter Data'
        serviceName: 'data'
        observablesEnabled: false
        port: 8181
        enableInstanceMetrics: 'true'
        capability: 'Data'
        jwt_prefix: '/jwt'
        documentation: '/services/data/latest/static/ui/index.html'
        owner: 'Decipher'
        version: 1.0.0
        jwt_prefix: /jwt
        # routes:
        #     - '/services/data/{{ data.version }}'
        #     - '/services/data/{{ data.version }}/'
        secret:
            enabled: true
            secret_name: sidecar-certs
            mount_point: /etc/proxy/tls/sidecar
            insecure: true
            secret_keys:
                cert: /etc/proxy/tls/sidecar/data-internal.crt
                key: /etc/proxy/tls/sidecar/data-internal.key
                ca: /etc/proxy/tls/sidecar/rootCA.crt
    data:
        catalogEnabled: true
        controlEnabled: true
        name: 'Grey Matter Data'
        serviceName: 'data'
        observablesEnabled: false
        port: 8181
        enableInstanceMetrics: 'true'
        capability: 'Data'
        jwt_prefix: '/jwt'
        documentation: '/services/data/latest/static/ui/index.html'
        owner: 'Decipher'
        version: 1.0.0
        jwt_prefix: /jwt
        # routes:
        #     - '/services/data/{{ data.version }}'
        #     - '/services/data/{{ data.version }}/'
        secret:
            enabled: true
            secret_name: sidecar-certs
            mount_point: /etc/proxy/tls/sidecar
            insecure: true
            secret_keys:
                cert: server.crt
                key: server.key
                ca: ca.crt
