---

# Create edge egress and ingress certs
- name: Create edge egress/ingress leaf certs # Only use when customer is not sending its own certs
  include_role:
    name: ansible-role-certs
  vars:
    service: "{{ item.service_name }}"
    certs_home_dir: "{{ item.certs_home_dir }}"
  loop:
    - {service_name: 'edge', certs_home_dir: '/etc/proxy/tls/sidecar'}
    - {service_name: 'edge', certs_home_dir: '/etc/proxy/tls/edge'}
  when: XDS_CLUSTER == 'edge'

- name: Run gm-proxy binary as a service
  include_role:
    name: ansible-role-systemd
    public: yes
    apply:
      tags:
        - proxy
  tags: proxy