---

- name: Create ijwt-secrets
  include_role:
    name: ansible-role-ijwt-secrets
  vars:
    create_ijwt_secret: yes

- name: Extract base64 values of ssl certs
  slurp:
    src: "{{ item.src }}"
  register: base64_values
  loop:
    - { src: /etc/proxy/tls/sidecar/internal-jwt-security.crt }
    - { src: '/etc/proxy/tls/sidecar/internal-jwt-security.key' }
    - { src: '/etc/proxy/tls/sidecar/rootCA.crt' }
    - { src: '/tmp/ijwt_secrets/jwtES512.key' }

# Restart redis server. Otherwise get connection error
- name: Restart Redis server
  service: 
    name: redis-server
    state: restarted 

- name: Create and run gm-jwt-security binary as a service
  include_role:
    name: ansible-role-systemd