---

- name: Create acert rootCA
  include_role:
    name: ansible-role-acert
    apply:
      tags:
        - control-api
  vars:
    create_rootCA: true
  tags: control-api

- name: Create gm-control-api leaf certs
  include_role:
    name: ansible-role-acert
    apply:
      tags:
        - control-api
  vars:
    acert_service: gm-control-api
  tags: control-api

- name: Extract base64 values of ssl certs
  slurp:
    src: "{{ item.src }}"
  register: base64_values
  loop:
    - { src: '/etc/proxy/tls/sidecar/gm-control-api-leaf-certificate.pem' }
    - { src: '/etc/proxy/tls/sidecar/gm-control-api-leaf-key.pem' }
    - { src: '/etc/proxy/tls/sidecar/gm-control-api-leaf-authority.pem' }
  tags: control-api

- name: Run gm-control-api binary as a service
  include_role:
    name: ansible-role-systemd
    public: yes
    apply:
      tags:
        - control-api
  tags: control-api