---

- name: Extract base64 values of ssl certs
  slurp:
    src: "{{ item.src }}"
  loop:
    - { src: '/etc/proxy/tls/sidecar/catalog.crt' }
    - { src: '/etc/proxy/tls/sidecar/catalog.key' }
    - { src: '/etc/proxy/tls/sidecar/rootCA.crt' }
  register: base64_values

- name: Create and run gm-catalog binary as a service
  include_role:
    name: ansible-role-systemd
  