---

- name: Create internal-jwt key
  shell: |
    openssl ecparam -genkey -name secp521r1 -noout -out {{ ijwt_secret_dir }}/jwtES512.key

- name: Extract pubkey of internal-jwt key
  shell: |
    openssl ec -in {{ ijwt_secret_dir }}/jwtES512.key -pubout -out {{ ijwt_secret_dir }}/jwtES512.key.pub

- name: Compress directory {{ ijwt_secret_dir }} into {{ ijwt_secret_dir }}.tgz
  archive:
    path: "{{ ijwt_secret_dir }}"
    dest: "{{ ijwt_secret_dir }}.tgz"

- name: Download {{ ijwt_secret_dir }}.tgz
  fetch:
    src: "{{ ijwt_secret_dir }}.tgz"
    dest: roles/ansible-role-ijwt-secrets/files/
    flat: yes