---

- name: Copy ijwt-secret file from local to server ## Temp task
  copy:
    src: "files/ijwt_secrets.tgz"
    dest: "/tmp"
    owner: "{{ service_user }}"
    group: "{{ service_group }}"
    mode: u=rwx,g=rx,o=rx

- name: Extract ijwt-secret file
  unarchive:
    src: "/tmp/ijwt_secrets.tgz"
    dest: "{{ ijwt_secret_dir }}"
    owner: "{{ service_user }}"
    group: "{{ service_group }}"
    extra_opts: [--strip-components=1]
    remote_src: yes