---

- name: Extract base64 values of ssl certs
  slurp:
    src: "{{ item }}"
  register: base64_values
  loop:
    - /etc/proxy/tls/sidecar/data-internal.crt
    - /etc/proxy/tls/sidecar/data-internal.key
    - /etc/proxy/tls/sidecar/rootCA.crt
    - /tmp/ijwt_secrets/jwtES512.key.pub
    - /etc/proxy/tls/sidecar/localhost.crt
    - /etc/proxy/tls/sidecar/localhost.key
    - /etc/proxy/tls/sidecar/intermediate.crt
  when: service == "data-internal"
  
- name: Run gm-data binary as a service
  include_role:
    name: ansible-role-systemd