---

- name: Build Infrastructure
  terraform:
    project_path: '../../terraform/'
    state: present
    force_init: true
    backend_config:
      region: "us-east-1"
      bucket: "{{ backend_bucket_name }}"
      key: "tfstate"