---

- name: Destroy Infrastructure
  terraform:
    project_path: '../../terraform/'
    state: absent
    force_init: true
    backend_config:
      region: "{{ backend_bucket_region }}"
      bucket: "{{ backend_bucket_name }}"
      key: "tfstate"