---

# Create gm-catalog configs
- hosts: tag_Name_gm_control_api
  user: ubuntu
  become: yes
  roles:
    - ansible-role-config
  vars:
    service_config: true
    value_edge_config: true
    SERVICE_NAME: catalog
    SERVICE_HOST_DNS: gm_catalog.greymatter
    GLOBAL_SECRET_ENABLED: true
    CLUSTER_PORT: 9080
    SSL_CONFIG_TRUST_FILE: /etc/proxy/tls/sidecar/gm-catalog-leaf-authority.pem
    SSL_CONFIG_CERTIFICATE_PATH: /etc/proxy/tls/sidecar/gm-catalog-leaf-certificate.pem
    SSL_CONFIG_KEY_PATH: /etc/proxy/tls/sidecar/gm-catalog-leaf-key.pem
    EDGE_SSL_CONFIG_TRUST_FILE: /etc/proxy/tls/sidecar/edge-leaf-authority.pem
    EDGE_SSL_CONFIG_CERTIFICATE_PATH: /etc/proxy/tls/sidecar/edge-leaf-certificate.pem
    EDGE_SSL_CONFIG_KEY_PATH: /etc/proxy/tls/sidecar/edge-leaf-key.pem

# Run gm-catalog and its sidecar
- hosts: tag_Name_gm_catalog
  user: ubuntu
  become: yes
  roles:
    - ansible-role-preparatory
    - ansible-role-proxy
    - ansible-role-catalog
  vars:
    XDS_CLUSTER: catalog
    XDS_HOST: gm_control.greymatter