---

# Run gm-control-api
- hosts: tag_Name_gm_control_api
  user: ubuntu
  become: yes
  roles:
    - ansible-role-preparatory
    - ansible-role-control-api
    - ansible-role-gmcli

# Run gm-control
- hosts: tag_Name_gm_control
  user: ubuntu
  become: yes
  roles:
    - ansible-role-preparatory
    - ansible-role-control