---

# Run gm-control-api
- hosts: tag_Name_gm_control_api
  user: ubuntu
  become: yes
  roles:
    - ansible-role-preparatory
    - ansible-role-control-api
    - ansible-role-gmcli
    - ansible-role-config
  vars:
    service_config: true
    value_edge_config: true
    edge_proxy_config: true
    SERVICE_NAME: control-api
    SERVICE_HOST_DNS: gm_control_api.greymatter
    GLOBAL_SECRET_ENABLED: false
    SSL_CONFIG_TRUST_FILE: /etc/proxy/tls/sidecar/gm-control-api-leaf-authority.pem
    SSL_CONFIG_CERTIFICATE_PATH: /etc/proxy/tls/sidecar/gm-control-api-leaf-certificate.pem
    SSL_CONFIG_KEY_PATH: /etc/proxy/tls/sidecar/gm-control-api-leaf-key.pem
    EDGE_SSL_CONFIG_TRUST_FILE: /etc/proxy/tls/sidecar/edge-leaf-authority.pem
    EDGE_SSL_CONFIG_CERTIFICATE_PATH: /etc/proxy/tls/sidecar/edge-leaf-certificate.pem
    EDGE_SSL_CONFIG_KEY_PATH: /etc/proxy/tls/sidecar/edge-leaf-key.pem
    CLUSTER_PORT: 5555

# Run gm-control
- hosts: tag_Name_gm_control
  user: ubuntu
  become: yes
  roles:
    - ansible-role-preparatory
    - ansible-role-control
  vars:
    config: "{{ lookup('file', '../group_vars/tf_ansible_vars_file.yml') | from_yaml }}"
    GM_CONTROL_AWS_VPC_ID: "{{ config.tf_vpc_id }}"
    GLOBAL_SECRET_ENABLED: false
    SSL_CONFIG_CERTIFICATE_PATH: /etc/proxy/tls/sidecar/gm-control-leaf-certificate.pem
    SSL_CONFIG_KEY_PATH: /etc/proxy/tls/sidecar/gm-control-leaf-key.pem

# Run gm-control-api sidecar proxy
- hosts: tag_Name_gm_control_api
  user: ubuntu
  become: yes
  roles:
    - ansible-role-proxy
  vars:
    XDS_CLUSTER: control-api
    XDS_HOST: gm_control.greymatter