---
# Create gm-ijwt configs
- hosts: tag_Name_gm_control_api
  user: ubuntu
  become: yes
  roles:
    - ansible-role-config
  vars:
    service_config: true
    value_edge_config: true
    SERVICE_NAME: internal-jwt-security
    SERVICE_HOST_DNS: gm_ijwt.greymatter
    GLOBAL_SECRET_ENABLED: true
    SSL_CONFIG_TRUST_FILE: /etc/proxy/tls/sidecar/gm-ijwt-leaf-authority.pem
    SSL_CONFIG_CERTIFICATE_PATH: /etc/proxy/tls/sidecar/gm-ijwt-leaf-certificate.pem
    SSL_CONFIG_KEY_PATH: /etc/proxy/tls/sidecar/gm-ijwt-leaf-key.pem
    EDGE_SSL_CONFIG_TRUST_FILE: /etc/proxy/tls/sidecar/edge-leaf-authority.pem
    EDGE_SSL_CONFIG_CERTIFICATE_PATH: /etc/proxy/tls/sidecar/edge-leaf-certificate.pem
    EDGE_SSL_CONFIG_KEY_PATH: /etc/proxy/tls/sidecar/edge-leaf-key.pem
    CLUSTER_PORT: 9443

# Run internal jwt and its sidecar
- hosts: tag_Name_gm_ijwt
  user: ubuntu
  become: yes
  roles:
    - ansible-role-preparatory
    - ansible-role-redis
    - ansible-role-internaljwt
    - ansible-role-proxy
  vars:
    XDS_CLUSTER: internal-jwt-security
    XDS_HOST: gm_control.greymatter
    CLIENT_JWT_ENDPOINT_PORT: 9443
    CLIENT_JWT_ENDPOINT_USE_TLS: true
    CLIENT_JWT_ENDPOINT_ADDRESS: 'localhost'