---
# Create gm-data configs
- hosts: tag_Name_gm_control_api
  user: ubuntu
  become: yes
  roles:
    - ansible-role-config
  vars:
    service_config: true
    value_edge_config: true
    SERVICE_NAME: data-internal
    SERVICE_HOST_DNS: gm_idata.greymatter
    GLOBAL_SECRET_ENABLED: true
    SSL_CONFIG_TRUST_FILE: /etc/proxy/tls/sidecar/gm-data-leaf-authority.pem
    SSL_CONFIG_CERTIFICATE_PATH: /etc/proxy/tls/sidecar/gm-data-leaf-certificate.pem
    SSL_CONFIG_KEY_PATH: /etc/proxy/tls/sidecar/gm-data-leaf-key.pem
    EDGE_SSL_CONFIG_TRUST_FILE: /etc/proxy/tls/sidecar/edge-leaf-authority.pem
    EDGE_SSL_CONFIG_CERTIFICATE_PATH: /etc/proxy/tls/sidecar/edge-leaf-certificate.pem
    EDGE_SSL_CONFIG_KEY_PATH: /etc/proxy/tls/sidecar/edge-leaf-key.pem
    CLUSTER_PORT: 9080

# Run gm-data and its sidecar
- hosts: tag_Name_gm_idata
  user: ubuntu
  become: yes
  roles:
    - ansible-role-preparatory
    - ansible-role-incert
    - ansible-role-mongodb
    - ansible-role-data
    - ansible-role-proxy
  vars:
    XDS_CLUSTER: data-internal
    XDS_HOST: gm_control.greymatter