---

- name: Ensure bash, OpenSSl, and libssl are the latest versions
  apt: name={{ item }} update_cache=true state=present
  with_items:
    - bash
    - openssl
    - libssl-dev
    - libssl-doc

- name: Install PostgreSQL
  apt: name={{ item }} update_cache=true state=present
  with_items:
    - postgresql
    - postgresql-contrib
    - libpq-dev
    - python3-psycopg2

- name: Update postgres db configuration
  action: copy src=templates/postgresql.conf.j2 dest=/etc/postgresql/10/main/postgresql.conf

- name: Update postgres client configuration
  action: template src=templates/pg_hba.conf.j2 dest=/etc/postgresql/10/main/pg_hba.conf
 
- name: Ensure the PostgreSQL service is running
  service: name=postgresql state=restarted enabled=yes

- name: Ensure database is created
  become: true
  become_user: postgres
  postgresql_db: name={{ db_name }}
             encoding='UTF-8'
             lc_collate='en_US.UTF-8'
             lc_ctype='en_US.UTF-8'
             template='template0'
             state=present

- name: Ensure user has access to the database
  become: true
  become_user: postgres
  postgresql_user: db={{ db_name }}
               name={{ db_user }}
               password={{ db_password }}
               priv=ALL
               state=present

- name: Ensure user does not have unnecessary privileges
  become: true
  become_user: postgres
  postgresql_user: name={{ db_user }}
               role_attr_flags=NOSUPERUSER,NOCREATEDB
               state=present